version: "3"
services:
    app:
        container_name: eventum-media-ms
        build: .
        ports:
            - "8443:8443"
        links:
            - mongo
    mongo:
        container_name: eventum-media-db
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"