version: "3"
services:
    app:
        container_name: eventum-media-ms
        build: .
        ports:
            - "3000:3000"
        links:
            - eventum-media-db
    mongo:
        container_name: eventum-media-db
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"